# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bebop_msgs/CommonAnimationsStateList.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class CommonAnimationsStateList(genpy.Message):
  _md5sum = "c89b289a8f935a33f0451effae3f9508"
  _type = "bebop_msgs/CommonAnimationsStateList"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# CommonAnimationsStateList
# auto-generated from up stream XML files at
#   github.com/Parrot-Developers/libARCommands/tree/master/Xml
# To check upstream commit hash, refer to last_build_info file
# Do not modify this file by hand. Check scripts/meta folder for generator files.
#
# SDK Comment: Paramaterless animations state list.

Header header

# Animation type.
uint8 anim_HEADLIGHTS_FLASH=0  # Flash headlights.
uint8 anim_HEADLIGHTS_BLINK=1  # Blink headlights.
uint8 anim_HEADLIGHTS_OSCILLATION=2  # Oscillating headlights.
uint8 anim_SPIN=3  # Spin animation.
uint8 anim_TAP=4  # Tap animation.
uint8 anim_SLOW_SHAKE=5  # Slow shake animation.
uint8 anim_METRONOME=6  # Metronome animation.
uint8 anim_ONDULATION=7  # Standing dance animation.
uint8 anim_SPIN_JUMP=8  # Spin jump animation.
uint8 anim_SPIN_TO_POSTURE=9  # Spin that end in standing posture, or in jumper if it was standing animation.
uint8 anim_SPIRAL=10  # Spiral animation.
uint8 anim_SLALOM=11  # Slalom animation.
uint8 anim_BOOST=12  # Boost animation.
uint8 anim_LOOPING=13  # Make a looping. (Only for WingX)
uint8 anim_BARREL_ROLL_180_RIGHT=14  # Make a barrel roll of 180 degree turning on right. (Only for WingX)
uint8 anim_BARREL_ROLL_180_LEFT=15  # Make a barrel roll of 180 degree turning on left. (Only for WingX)
uint8 anim_BACKSWAP=16  # Put the drone upside down. (Only for WingX)
uint8 anim
# State of the animation
uint8 state_stopped=0  # animation is stopped
uint8 state_started=1  # animation is started
uint8 state_notAvailable=2  # The animation is not available
uint8 state
# Error to explain the state
uint8 error_ok=0  # No Error
uint8 error_unknown=1  # Unknown generic error
uint8 error

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  # Pseudo-constants
  anim_HEADLIGHTS_FLASH = 0
  anim_HEADLIGHTS_BLINK = 1
  anim_HEADLIGHTS_OSCILLATION = 2
  anim_SPIN = 3
  anim_TAP = 4
  anim_SLOW_SHAKE = 5
  anim_METRONOME = 6
  anim_ONDULATION = 7
  anim_SPIN_JUMP = 8
  anim_SPIN_TO_POSTURE = 9
  anim_SPIRAL = 10
  anim_SLALOM = 11
  anim_BOOST = 12
  anim_LOOPING = 13
  anim_BARREL_ROLL_180_RIGHT = 14
  anim_BARREL_ROLL_180_LEFT = 15
  anim_BACKSWAP = 16
  state_stopped = 0
  state_started = 1
  state_notAvailable = 2
  error_ok = 0
  error_unknown = 1

  __slots__ = ['header','anim','state','error']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,anim,state,error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CommonAnimationsStateList, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.anim is None:
        self.anim = 0
      if self.state is None:
        self.state = 0
      if self.error is None:
        self.error = 0
    else:
      self.header = std_msgs.msg.Header()
      self.anim = 0
      self.state = 0
      self.error = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.anim, _x.state, _x.error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.anim, _x.state, _x.error,) = _get_struct_3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.anim, _x.state, _x.error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.anim, _x.state, _x.error,) = _get_struct_3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
