(cl:in-package bebop_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          XAXISCALIBRATION-VAL
          XAXISCALIBRATION
          YAXISCALIBRATION-VAL
          YAXISCALIBRATION
          ZAXISCALIBRATION-VAL
          ZAXISCALIBRATION
          CALIBRATIONFAILED-VAL
          CALIBRATIONFAILED
))